/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OOrgSlugIndexRouteImport } from './routes/o/$orgSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugIndexRoute = OOrgSlugIndexRouteImport.update({
  id: '/o/$orgSlug/',
  path: '/o/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o/$orgSlug': typeof OOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/o/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/o/$orgSlug'
  id: '__root__' | '/' | '/o/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OOrgSlugIndexRoute: typeof OOrgSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/': {
      id: '/o/$orgSlug/'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OOrgSlugIndexRoute: OOrgSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
